plugins {
    id 'com.android.application' version '8.0.2' apply false
    id 'com.android.library' version '8.0.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.10' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

// TestRigor-specific build task
tasks.register('buildForTestRigor') {
    dependsOn ':app:assembleDebug'
    doLast {
        println "APK built for TestRigor"
    }
}
