source 'https://cdn.cocoapods.org/'
platform :ios, '26.0'
use_frameworks!

target 'BabelWords' do
  # Google Mobile Ads SDK (AdMob interstitial, rewarded, app open ads)
  pod 'Google-Mobile-Ads-SDK', '~> 11.0'

  # User Messaging Platform (GDPR/EEA consent)
  pod 'GoogleUserMessagingPlatform', '~> 2.2'

  # Firebase Analytics + Crashlytics
  pod 'FirebaseAnalytics', '~> 11.0'
  pod 'FirebaseCrashlytics', '~> 11.0'

  target 'BabelWordsTests' do
    inherit! :search_paths
  end

  target 'BabelWordsUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '26.0'
      config.build_settings['SWIFT_VERSION'] = '6.0'
      # Avoid duplicate symbols with Google Mobile Ads / UMP
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
    end
  end
end
