# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'LinguaVibe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Google Mobile Ads SDK
  pod 'Google-Mobile-Ads-SDK', '~> 11.0'
  
  # Google UMP (User Messaging Platform) for GDPR consent
  pod 'GoogleUserMessagingPlatform', '~> 2.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
